### ISSUE TITLE
Avoid saving `lcd`

### ISSUE THREAD

**Issue by rafi** [zhimsel/vim-stay#10]
How could I make vim-stay avoid saving `lcd` variable?
Reading the doc, seems the _Autocommand API_ might be a good direction,
but I'm not sure how to work it out. Could you help? :)

**Comment by kopischke** [comment]
As [documented in the help](https://github.com/kopischke/vim-stay/blob/master/doc/vim-stay.txt#L164-L169), the persistent local working directory is a side effect of how Vim’s view sessions work. If you have a version of Vim recent enough to support `haslocaldir()`, you can indeed work around that using _vim-stay_’s autocommand API. One way would be to temporarily suppress the local working directory when saving the session:

``` vim
augroup stay_no_lcd
  autocmd!
  autocmd User BufStaySavePre  if haslocaldir() | let w:lcd = getcwd() | cd - | cd - | endif
  autocmd User BufStaySavePost if exists('w:lcd') | execute 'lcd' fnameescape(w:lcd) | unlet w:lcd | endif
augroup END
```

As you will have noticed, this is somewhat hacky, needing an actual, redundant directory change (the double `cd -`) because of the idiotically awkward way Vim implements working directory handling. As it is also incompatible with all but the most recent Vim versions, I won’t add this hack to _vim-stay_, much as I would like to offer an option to suppress persisting the local working directory and / or the local arglist.

**Comment by rafi** [comment]
Works like a charm so far, thank you for the complete solution!

**Comment by kopischke** [comment]
Good to hear that. One important caveat: currently, the `BufStay*Post` events do not fire when errors occur while saving / loading views; the above hack thus will leave you with your current local working directory unset in such a case (I’m thinking about changing this behaviour as the Pre / Post event pairs are also used in the integration modules to handle third party state).

**Comment by kopischke** [comment]
PS: I’d be interested in knowing why you prefer to suppress local working directory persistence. Would you care to elucidate?

**Comment by rafi** [comment]
When dealing with multiple projects, I like designating each project a tab and change each tab's `lcd` to its project's directory. I want to suppress `lcd`'s persistency because:
1. I don't like the thought of my `lcd` changing without my knowledge, unless I do it manually.
2. Somehow together with [xolox/vim-session](https://github.com/xolox/vim-session) I experienced wrongfully mixed `lcd` values which led me here after discovering `lcd` setting entries in my vim-stay view files.

**Comment by kopischke** [comment]
Point 1 is a valid concern – I find  the local working directory restoration a bit disorienting myself at times, which is why I have toyed with remedies. Unluckily, all of these are gross hacks of the kind I showed above, thanks to Vim’s geriatrically demented `cwd` handling.

Point 2 is one where I’d been remiss not to warn you that _vim-session_ is not entirely without problems of its own; in its efforts to not inherit the warts of Vim’s session management, it has re-implemented all of that feature instead of piggy-backing on it. I found it often left my Vim in a confused and confusing state, which is why I removed it from my setup.

**Comment by rafi** [comment]
Thanks for all this viable information. About _xolox/vim-session_ - it's been acting pretty good for me. I've also ported Shougo's session unite source to use _vim-session_. Out of curiousity - what session persistency alternative are you using now?

**Comment by kopischke** [comment]
> Out of curiousity - what session persistency alternative are you using now?

None, really: per project tabs with a tab scoped working directory courtesy of [my fork of Kana’s _vim-tabpagecd_](https://github.com/kopischke/vim-tabpagecd), _vim-stay_ for file level persistence, but mostly simply leaving my MacVim instance running all the time suffice to my needs :).

**Comment by blueyed** [comment]
> As it is also incompatible with all but the most recent Vim versions, I won’t add this hack to vim-stay, ...

You could have a version / patch check for this - if it's known which version is required.

For what it's worth, I am not getting a `lcd` in the view file with recent versions of vim/neovim.

For older versions it might be even possible to remove it, based on `haslocaldir()` (which might need a check to be available though also).

**Comment by kopischke** [comment]
@blueyed the whole local working directory issue is some thing I am still mulling possible solutions over. One thing I want to avoid is adding features that only work in certain Vim versions and patch levels. A consistent set of features for all versions of Vim _stay_ supports is a design priority of mine, hence the statement you quoted above.

**Comment by blueyed** [comment]
@kopischke 
Any update on this?
As for the workaround above, it should take into account and prefer `:tcd` over `:cd` I guess if it exists?!

**Comment by blueyed** [comment]
What about removing the `lcd` from the mkview in the first place (by rewriting it)?! (if `haslocaldir()` is false)

**Comment by kopischke** [comment]
@blueyed absolutely none; as you probably have noticed, development of my plugins has been dormant for quite a while now, mostly because life has left me precious little time for dev work these last two years. Sorry for that.

For what it’s worth, I will add that even should I find time to pick up development again, I still probably would not go the rewriting route: keeping the breakage potential low by sticking to a well defined API (in this case: the `mkview` / `loadview` commands) instead of fiddling with internals has pretty much been a design principle for my plugins.

**Comment by blueyed** [comment]
Understood.
FWIW the following makes the workaround work with Neovim:
```vim
augroup stay_no_lcd
  autocmd!
  if exists(':tcd') == 2
    autocmd User BufStaySavePre  if haslocaldir() | let w:lcd = getcwd() | exe 'cd '.fnameescape(getcwd(-1, -1)) | endif
  else
    autocmd User BufStaySavePre  if haslocaldir() | let w:lcd = getcwd() | cd - | cd - | endif
  endif
  autocmd User BufStaySavePost if exists('w:lcd') | execute 'lcd' fnameescape(w:lcd) | unlet w:lcd | endif
augroup END
```

**Comment by jdsutherland** [comment]
Any updates on this? I was noticing unexpected directory changes happening and traced it to this plugin. I tried using @blueyed's fix for nvim but the issue seems to persist.
