### ISSUE TITLE
Prevent changing directory when restoring view.

### ISSUE THREAD

**Issue by sergei-dyshel** [zhimsel/vim-stay#11]
According to my observations and [Vim's help](http://vimdoc.sourceforge.net/htmldoc/starting.html#:mkview) `mkview` always adds `lcd ...` command to created file. This can lead to unexpected current directory changes when same file is opened in different "sessions" (projects etc.)
A possible workaround would be to remove `lcd` line from the generated script.

**Comment by kopischke** [comment]
Ah, yes, the `lcd` issue. Actually, it’s a known quirk of `:mkview` I documented in [the plugin help](https://github.com/kopischke/vim-stay/blob/master/doc/vim-stay.txt)’s <strike>FAQ</strike>Troubleshooting section. The maddening thing about it is that it is both inconsistent (according to the Vim help, it should only store actually set local working directories, but that  seems to be wishful thinking: I’ve noticed it often, but, crucially, not always, switches when there is no need to) and hard to fix (due to the train wreck Vim’s working directory API is). 

I’ll ponder approaches to fixing this (again – it’s been sitting in the private Trello for this plugin for quite some time now), but I can’t promise anything ATM.

**Comment by kopischke** [comment]
Until I get around to this, you might be interested in the workaround I suggested in #10 .

**Comment by sergei-dyshel** [comment]
Thanks! This is much better than the workaround that I've been using - save _cwd_ on Vim start and _cd_ to it on each file opening.

**Comment by blueyed** [comment]
JFI: Neovim has tab local directories now additionally: https://github.com/neovim/neovim/commit/5ebffaae4e6c08630b705b5994a509a08cbecce6

**Comment by kopischke** [comment]
Thanks, but I was aware of that, [having been part of the discussion that led to the feature](https://github.com/neovim/neovim/pull/3229) ;). Unluckily, neither that feature nor [Vim’s recent `getcwd()` patch](https://github.com/vim/vim/commit/c970330676eaae7ba7cd05cfa46df5a413853ef9) affect my previous arguments much. I have been pondering a different approach for a while now, and might integrate it into the 1.5 release. Speaking of which, did you have an opportunity to look at #13?
