### ISSUE TITLE
Errors from mkview with view files written through "sudo vim"

### ISSUE THREAD

**Issue by blueyed** [zhimsel/vim-stay#14]
If `sudo vim` has been used initially for a file (where the view file gets created), you will end up with files that are owned by root.

When editing it without `sudo` later, the following error happens (through the call  to `mkview`):

```
Error detected while processing function stay#view#make:
line   14:     
E190: Cannot open "/home/user/.nvim/view/=+etc=+apt=+sources.list.d=+nodesource.list=" for writing
```

It might be feasible to skip creation of views (calling `:mkview`) in case there is no view file already (and therefore a new one would be created).  But I don't know if that can be detected.

Neomru uses the following code to detect usage of `sudo` and then skips writing its MRU list:

``` vim
function! s:is_sudo() "{{{
  return $SUDO_USER != '' && $USER !=# $SUDO_USER
        \ && $HOME !=# expand('~'.$USER)
        \ && $HOME ==# expand('~'.$SUDO_USER)
endfunction"}}}
```

([source](https://github.com/Shougo/neomru.vim/blob/master/autoload/neomru.vim#L447-L451))

I think it might be fine to skip

**Comment by kopischke** [comment]
Thanks for bringing this to my attention. I am not sure simply skipping view session creation for `sudo` users is the right way to deal with this, however – or if there even is one. My thinking goes something like this:
- at the root (forgive the pun) this is an issue with Vim’s half hearted approach to view session file management. View session files inside a common `&viewdir` are not disambiguated by user, which will not only lead to problems with `sudo`, but also in case the directory is located in a shared folder (not unthinkable if you try to share config files across accounts). That last case is undetectable by the code you kindly suggested.
- even disregarding that, simply disabling the plugin when using `sudo` might be the wrong approach. Granted it feels right for typical dev workflows, but what about sysadmins? They tend to use `sudo` a lot out of necessity, excluding them from plugin use doesn’t strike me as the obvious choice here just because my (and I assume: your) needs are different.
- even disregarding **that**, or assuming we add an option for it (gah), this would add a platform dependency _vim-stay_ doesn’t currently have. Unless things changed a lot since I last checked, Windows has its own concept of privilege levels and per process escalation which have nothing to do with `sudo`.

To make a long story short, I am loath to add a workaround to a Vim design flaw that privileges a specific workflow on certain platforms. What that does leave I am not sure, as that error **is** hugely annoying… thoughts?

**Comment by blueyed** [comment]
See https://github.com/kopischke/vim-stay/pull/16 - for now it seems to be a good idea to catch it and turn it into a warning.
