### ISSUE TITLE
vim-stay changes foldmethod

### ISSUE THREAD

**Issue by senft** [zhimsel/vim-stay#3]
Hi,
I tried to use vim-stay to restore my folds, but apparently it changes the `foldmethod` to `diff`. I usually use `foldmethod=syntax`. Is there any way to keep my foldmethod?
thanks!

**Comment by kopischke** [comment]
That is rather unexpected: _vim-stay_ never touches the `foldmethod`, and Vim’s view session mechanism only stores manual fold state (if “folds” is in `viewoptions`, which is the default). What is the output of

``` vim
:1verbose set fdm?
```

**Comment by kopischke** [comment]
Ping @senft.

**Comment by senft** [comment]
Ah, I am sorry. The error was caused by "old" view files from before using vim-stay. I deleted those and everything works fine now.

Although I now get this error when I start vim:

```
Error detected while processing function pathogen#helptags:
line    4:
E154: Duplicate tag "BufStayLoadPost" in file /home/jln/.vim/bundle/vim-stay/doc/vim-stay.txt
Press ENTER or type command to continue
```

**Comment by kopischke** [comment]
Glad to hear it is solved; the next release will contain some extra documentation about `viewoptions` and possible trouble using them. 

The error is … correct: there is a duplicate help tag in the docs, will be fixed in the next release too. I’ve put that one up in a new issue (#7), closing this one.
