### ISSUE TITLE
Error when opening a file (v1.4.0)

### ISSUE THREAD

**Issue by choco** [zhimsel/vim-stay#30]
Hi, I was testing the 1.4.0 release branch and sometimes I'm getting this error when opening a file.

![untitled](https://cloud.githubusercontent.com/assets/85527/16813772/5b7c48bc-4933-11e6-8ecb-31a95c7566fb.png)

Sorry for reporting issues on a unreleased version, but some of the bug fix included in that are really useful for me!

**Comment by kopischke** [comment]
Thanks for reporting this: I can see where the issue is and will fix as soon as I have some time to get back to _stay_. If you need a quick fix,  you can change [this line](https://github.com/kopischke/vim-stay/blob/release/1.4.0/autoload/stay/view.vim#L110) to:

``` vim
if get(l:, 'did_load_view', 0) isnot 1 && exists('l:stay_loaded_view')
```

_EDITED as per [@ntcong’s amendment](https://github.com/kopischke/vim-stay/issues/30#issuecomment-236792477)._

**Comment by ntcong** [comment]
if anyone watching this, the quick fix should be

```vim
if get(l:, 'did_load_view', 0) isnot 1 && exists('l:stay_loaded_view')
```
