### ISSUE TITLE
Does this plugin automatically clear out views beyond a certain date

### ISSUE THREAD

**Issue by alphaCTzo7G** [zhimsel/vim-stay#41]
The `restore_view.vim` plugin doesn't automatically clear views as a result the view folder grows in size. At some point or other its starts causing problems. For example.. I started having problems with `buffexplorer` because I had a large view folder.

It seems there is no development on the `restore_view` plugin. Last commit was in 2014/5: https://github.com/vim-scripts/restore_view.vim, https://github.com/senderle/restoreview depending in which one you look at.

So, either I have to write a function in VIM which automatically takes care of this or start a cron job. 

It seems this plugin is similar to `restore_view` but attempts to improve on it. Does this plugin automatically removes view files beyond a certain time.. to cause less issues: https://github.com/jlanzarotta/bufexplorer/issues/72, https://github.com/amix/vimrc/issues/426.

I also use the `vim-obsession` plugin for session management. Does this plugin attempt to do both sessions and view management simultaneously? Are there any clashes between this plugin and `vim-obsession`?

**Comment by zhimsel** [comment]
Hey! As far as I'm aware (I'm the new maintainer for this repo and not 100% familiar with the code yet), there is no automatic cleanup functionality. There is, however, [a function to _manually_ clean the viewdir](https://github.com/zhimsel/vim-stay/blob/5ce6dd2/autoload/stay/viewdir.vim#L10-L23). You can likely set up an `autocmd` to do this automatically (though I'm not sure if vim can do `au`s by time. If you decide to write anything up, please feel free to submit a PR to include that functionality for this plugin.

> Does this plugin attempt to do both sessions and view management simultaneously? Are there any clashes between this plugin and vim-obsession?

I don't believe `vim-stay` uses _sessions_ in the way that `vim-obsession` does. However, I wouldn't definitively say there are no clashes without some testing. You can find the internal functions for `vim-stay` that handle view session saving and loading in [`view.vim`](https://github.com/zhimsel/vim-stay/blob/master/autoload/stay/view.vim).

**Comment by kopischke** [comment]
Zach is correct on both counts (hi, former maintainer here): there is a command for nuking your `viewdir`, but nothing fine grained or automatic, for the simple reason I never found a reliable cross platform way (`sh` command scripts do not work on Windows, mostly). You might find the script linked to in #38 of interest if you are on a \*nix system.

Also, stay uses only what Vim calls “view sessions”, which are not the same thing as full fledged sessions (though I can see how the nomenclature could be confusing; blame Bram 😉); conflicts between full sessions and view sessions can arise in the sense that view sessions are essentially a subset of full sessions and there is no way to tell which of the two should “win” when their settings differ. Because of this, [the upcoming 1.4 release of stay always defers to full session loading](https://github.com/zhimsel/vim-stay/blob/87c0b0ba8a0a4f16c0cee34090b29af200bd5d3c/plugin/stay.vim#L58) (that is introduced by commit ~~047936c4b1ad21c94413ac610a8f225dbb307f1f~~657451a058356700098c2409b10f380ced78e4fe) on the assumption that a stored full session is a state the user wishes to have.

**Comment by zhimsel** [comment]
I'm gonna close this for now. If you have any further questions, feel free to comment and/or reopen.

**Comment by alphaCTzo7G** [comment]
@zhimsel , @kopischke .. appreciate it.. Sorry for the late reply. That pretty much solves it. I pretty much only use my `heavy VIM` config on my Ubuntu Workstation.. and no config for any other servers. So this works great..
