### ISSUE TITLE
vim-stay error E867: (NFA) Unknown operator '\zh'

### ISSUE THREAD

**Issue by skt041959** [zhimsel/vim-stay#46]
Hi Developer,
When I use this plugin in Windows, I tend to get this error when opening files.

I tried to debug it, and comment out the `catch "other errors` block of `stay#view#load(winid)`, I get the following verbose output of vim:

```
E867: (NFA) Unknown operator '\zh'
E68: Invalid character after \z
No matching autocommands

Error detected while processing function <SNR>9_LoadView[8]..stay#view#load:
line   31:
E867: (NFA) Unknown operator '\zh'
E68: Invalid character after \z
```

The "zh" string is the starting of my username, so I think it's caused by the un-escape window path.
Would you please give it a fix ?

Thanks

**Comment by zhimsel** [comment]
I don't use vim on Windows, so it'll be hard for me to test, but I can do what I can to look into it when I have the time. No promises, though.

I'm always happy to accept Pull Requests, if you'd like to take a stab at fixing this yourself, too.

**Comment by kopischke** [comment]
Fixing this might be difficult as the cause is totally unclear: the offending regex exception seems to stem from this one off `SourcePre` autocommand: https://github.com/zhimsel/vim-stay/blob/287c80bf6f151a3561800db184610cf576b0374d/autoload/stay/view.vim#L79-L81

(Vim’s exception line numbers are function relative, if I remember correctly, one of the many things that drove me out of Vim hacking). @skt041959 may be right in blame backslashes in file names on Windows systems, but without knowing the exact Vim version, feature set, and relevant settings, and without access to a Windows machine, this is almost impossible to debug, never mind “fix”.

**Comment by zhimsel** [comment]
I'm suspecting you're correct, @kopischke.

@skt041959 I'll leave this open in the meantime, but I can't guarantee I'll be able to fix this myself. I'd whole-heartedly welcome you debugging this and pushing a fix yourself.

----

For when I get some spare time to investigate this, I need to know some more about your environment:
1. What Windows version?
1. What vim/neovim/gvim version?
1. Could you supply your `vimrc`?
1. What's the username (the one that starts with `zh`?)
1. What steps could I do to replicate the issue you're having?

**Comment by kopischke** [comment]
I don’t have the option of doing so myself (what with not working with, or hacking on, Vim anymore), but thinking this through there is one thing you could try, @skt041959: change this line 
https://github.com/zhimsel/vim-stay/blob/287c80bf6f151a3561800db184610cf576b0374d/autoload/stay/view.vim#L79

to

```vim
let l:pattern = fnameescape(s:viewdir.path).'*'.fnamemodify(bufname('%'), ':t').'*'
```

and see if it helps. If it does, @zhimsel would have to check if this patch  impacts operations on non-Windows systems …

**Comment by skt041959** [comment]
@kopischke @zhimsel I'm glad to debug this with your suggestion. 

For reproducing, I have tried this minimal vimrc, and the issue appears when opening a file with a view file to load.
```
call plug#begin()
     Plug 'kopischke/vim-stay'
call plug#end()
```
Environment

1. Windows 10
2. Neovim version is 0.3.3. I will try with vim8 later to see whether it can be reproduced.
3. My username is `zhentao`

@kopischke I have tried your fix, it doesn't work.

Thanks

**Comment by skt041959** [comment]
I can reproduce this issue with vim-8.1.0877.

**Comment by kopischke** [comment]
> I have tried your fix, it doesn't work.

@skt041959 Just to make sure (because this is the only part of the `load` function where we use a path I can see): you modified the code of your copy of _stay_ and restarted Neovim, loading the modified plug-in? Oh, BTW, you don’t need to comment out parts of the code to see error messages, just set `g:stay_verbosity=1`.

**Comment by skt041959** [comment]
@kopischke 

I did some experiments to replace the `l:pattern` with other strings

- `C:\\Users\\zhentao\\*test.txt*`  This won't trigger the error
- `C:\Users\zhentao\*test.txt*` This will trigger the error

I put a `verbose echo l:pattern` to output it with your fix, and get the second pattern.
I'm wondering why the `fnameescape()` didn't escape the backslashes ?

**Comment by skt041959** [comment]
@kopischke 

The second pattern also can't trigger this SourcePre event, unless I replace with 

- C:/Users/zhentao/test.txt

It works pretty well. That I think we need to replace all backslashes with slashes in the l:pattern

**Comment by kopischke** [comment]
@skt041959 I think we are getting close to a solution. Could you tell me your `shellslash` and `isf` settings? And does the first pattern (with the escaped backslashes) trigger the `SourcePre` event?

**Comment by skt041959** [comment]
@kopischke 

`isfname=@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=`
`noshellslash`

Sorry, I mean the first pattern can't trigger SourcePre event. The second pattern will trigger the E867 error.

**Comment by kopischke** [comment]
⭐️ – I think I know what is going on: when designing _stay_ without access to a Windows Vim version, I assumed file name patterns in autocommands use platform conventions on Windows unless `shellslash` is set, so I added the `s:slash` function

https://github.com/zhimsel/vim-stay/blob/287c80bf6f151a3561800db184610cf576b0374d/autoload/stay/view.vim#L141-L149

and inserted a substitution step to normalise all file paths accordingly

https://github.com/zhimsel/vim-stay/blob/287c80bf6f151a3561800db184610cf576b0374d/autoload/stay/view.vim#L75

However, it seems autocommands always use forward slashes internally, so what that line should actually do is replace all slashes and backslashes in the path by a forward slash, i.e.

````vim
let s:viewdir.path = substitute(s:viewdir.option, '\v[/\\]+$', '/', '')
````
(note we still need to replace sequences of slashes by a slash, to catch badly formatted options; however, we should replace _one or more_ (`+`), not _zero or more_ (`*`), because if Vim’s regex engine should ever start to behave differently when you match an empty string this could end with us actually interspersing the path with random slashes …).

I suppose nobody caught this until now because most _stay_ users are either not on Windows, or have `shellslash` set, which would have produced a correct pattern in  the current implementation.

@skt041959 could you try patching line 75 as shown above and see if that helps? @zhimsel If it does, you can also get rid of the whole `s:slash` definition block, as it is only ever used in this spot.

------
As a, hopefully final, footnote: the fact I still have such a perversely intimate knowledge of Vim’s internals years after having stopped hacking on, or even using, Vim, tells you all you need to know about plug-in development on that platform 🤯.

**Comment by skt041959** [comment]
@kopischke  Unfortunately, It doesn't work :(

**Comment by skt041959** [comment]
@kopischke  
The following line works
```
let s:viewdir.path = substitute(s:viewdir.option, '\v[/\\]+', '/', 'g')
```

**Comment by skt041959** [comment]
@kopischke  I tried `set shellslash`, it doesn't work :(

**Comment by kopischke** [comment]
@skt041959 oh wow, that is a bug: that `g` should have been in there all along! I suspect the only reason this whole issue has gone unnoticed for so long is that the default `viewdir` path on Windows uses  slashes, not backslashes. I assume yours is somehow customised to result in a path with backslashes?

Anyway, the final word would be to patch line 75 to read

```vim
let s:viewdir.path = substitute(s:viewdir.option, '\v[/\\]+', '/', 'g')
```

and to get rid of the now obsolete `s:slash` block. @zhimsel I can check if I can submit this entirely through the web, but you’d still have to integrate and test the patch. Is that OK with you?

**Comment by zhimsel** [comment]
@kopischke that's fine with me! Thanks so much for taking such a deep look at this.

**Comment by skt041959** [comment]
@zhimsel I tested the branch, it works fine.

**Comment by kopischke** [comment]
@skt041959 I’ve done a bit more thinking and it seems #47 is not ready for prime time yet. Would you mind doing a bit more testing for me? If yes, would you please:

1. Paste the output of `:echo &viewdir` on your system;
2. Paste the literal command your `viewdir` is set with, if any;
3. Change that to set it to a Windows path with a space inside (escaping the both the space and the path separator backslashes with one extra backslash) and Paste the command here;
5. Repeat step 1.

That would be enormously helpful;as I said, I have no access to Vim, much less on Windows, and I don’t want to push out another half functional version or introduce regressions in #47 (you can follow my reasoning over there, if you feel like it),

**Comment by skt041959** [comment]
@kopischke Sorry for delay update.

- For nvim, the `viewdir` is `C:\Users\zhentao\AppData\Local\nvim-data\view`
- For vim8, the `viewdir` is `C:\Users\zhentao\scoop\apps\vim\current/vimfiles/view`, but this path doesn't exists even the function works. Seems the cursor location is stored in viminfo file.

I add following in the test vimrc/init.vim file
```viml
set viewdir=C:/Users/zhentao/vimfiles/vi\ ew
```
Now the `viewdir` is `C:/Users/zhentao/vimfiles/vi ew`

**Comment by kopischke** [comment]
@skt041959 thanks for reporting this! The mix of slashes and backslashes is a bit surprising, but that can be handled too. I’ve added a commit to #47 to address this, please head over to the PR for details and instructions for testing.
